version: '3'

services:
  web-app:
    build:
      context: .
      dockerfile: ./docker/alpine/Dockerfile
    container_name: web-app
    expose:
      - "9000"
    ports:
      - "8000:8000"
    volumes:
      - ".:/var/www/"
    command: bash -c
      "php artisan cache:clear
      && php artisan config:clear
      && php artisan route:clear
      && php artisan config:cache
      && php artisan serve --host 0.0.0.0"
    depends_on:
      - postgres
    restart: always
    networks:
      - app-network

  postgres:
    image: postgres:9.4
    container_name: postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: pg!lol!2019
    ports:
      - 5432:5432
    volumes:
      - "./postgres/dbdata:/var/lib/postgresql/data"
    networks:
      - app-network

  pgadmin:
    image: thajeztah/pgadmin4
    container_name: pgadmin
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: postgres
      PGADMIN_DEFAULT_PASSWORD: pg!lol!2019
      PGADMIN_ENABLE_TLS: "False"
    ports:
      - 5050:5050
    depends_on:
      - postgres
    networks:
      - app-network

networks:
 app-network:
  driver: bridge
